export const placeOrderButton ="//button[@class='btn btn-success']"
export const name="//div//label[text()='Name:']"
export const country="//div//label[text()='Country:']"
export const city="//div//label[text()='City:']"
export const creditcard="//div//label[text()='Credit card:']"
export const month="//div//label[text()='Month:']"
export const year="//div//label[text()='Year:']"
export const purchase="//button[text()='Purchase']"
export const okbtn="//button[@class='confirm btn btn-lg btn-primary']"
export const successfullmsg="//h2[text()='Thank you for your purchase!']"
export const close_btn="(//button[@class='btn btn-secondary'])[3]"